services:
  - type: web
    name: arqueologia-avatar-app
    runtime: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      # Todas as chaves devem ser cadastradas como 'secrets' no painel do Render
      - key: GEMINI_API_KEY
        fromSecret: true
      - key: SUPABASE_URL
        fromSecret: true
      - key: SUPABASE_ANON_KEY
        fromSecret: true
      - key: SUPABASE_SERVICE_ROLE_KEY
        fromSecret: true
      # Alterado para 'fromSecret' para usar seu banco de dados externo do Supabase
      - key: DATABASE_URL
        fromSecret: true
      - key: FLASK_ENV
        value: production
      # É uma boa prática definir a SECRET_KEY como um segredo também
      - key: SECRET_KEY
        fromSecret: true
      - key: CORS_ORIGINS
        value: "*"

