services:
  - type: web
    name: arqueologia-avatar-app
    env: python
    plan: free
    # Altere esta linha para o novo buildCommand
    buildCommand: ./build.sh
    startCommand: gunicorn --bind 0.0.0.0:$PORT src.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      # ... suas outras variáveis de ambiente ...
