services:
  - type: web
    name: arqueologia-avatar-app
    runtime: python
    plan: free
    branch: main
    # O comando de build agora instala as dependências diretamente.
    # Isso garante que ele sempre execute a partir do diretório raiz correto.
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT src.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        fromSecret: true
      - key: SUPABASE_URL
        fromSecret: true
      - key: SUPABASE_ANON_KEY
        fromSecret: true
      - key: SUPABASE_SERVICE_ROLE_KEY
        fromSecret: true
      - key: DATABASE_URL
        fromDatabase:
          name: sua-base-de-dados # <-- SUBSTITUA PELO NOME REAL DO SEU BANCO DE DADOS
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: "*"

