services:
  - type: web
    name: arqueologia-avatar-app
    # A alteração principal é usar 'runtime' em vez de 'env' para ser mais explícito.
    runtime: python 
    plan: free
    branch: main
    buildCommand: bash ./build.sh
    startCommand: gunicorn --bind 0.0.0.0:$PORT src.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        fromSecret: true # É mais seguro usar segredos para chaves de API
      - key: SUPABASE_URL
        fromSecret: true
      - key: SUPABASE_ANON_KEY
        fromSecret: true
      - key: SUPABASE_SERVICE_ROLE_KEY
        fromSecret: true
      - key: DATABASE_URL
        fromDatabase:
          name: sua-base-de-dados # Substitua pelo nome do seu banco de dados no Render
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: "*"

