services:
  - type: web
    name: arqueologia-avatar-app
    runtime: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    # O comando --chdir muda o diretório para 'src' antes de iniciar.
    # Isso resolve o erro 'ModuleNotFoundError' ao garantir que 'main:app'
    # seja encontrado no caminho correto.
    startCommand: gunicorn --chdir src main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      # Todas as chaves devem ser cadastradas como 'secrets' no painel do Render
      - key: GEMINI_API_KEY
        fromSecret: true
      - key: SUPABASE_URL
        fromSecret: true
      - key: SUPABASE_ANON_KEY
        fromSecret: true
      - key: SUPABASE_SERVICE_ROLE_KEY
        fromSecret: true
      - key: DATABASE_URL
        fromSecret: true
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        fromSecret: true
      - key: CORS_ORIGINS
        value: "*"

